# mysql
# nginx
# wordpress
# php-fpm

---
######################################################################### mysql
- name: Install Mysql package
  yum: name={{ item }} state=present
  with_items:
    - mysql-devel
    - mysql-server
    - MySQL-python
    - libselinux-python
    - libsemanage-python

- name: Configure SELinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes
  when: ansible_selinux.status == "enabled"

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mysql

- name: Start Mysql Service
  service: name=mysqld state=started enabled=yes

######################################################################## nginx
- name: Install nginx
  yum: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy nginx configuration for wordpress
  template: src=mime.types dest=/etc/nginx/mime.types
  notify: restart nginx

- name: Copy nginx configuration for wordpress
  template: src=conf.d/default.conf.j2 dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Start nginx Service
  service: name=nginx state=started enabled=yes

######################################################################## wordpress
- name: Download Wordpress
  get_url: url=http://ja.wordpress.org/wordpress-{{ wp_version }}.tar.gz dest=/srv/wordpress-{{ wp_version }}.tar.gz

- name: Extract archive
  command: chdir=/srv/ /bin/tar xvf wordpress-{{ wp_version }}.tar.gz creates=/srv/wordpress/index.php

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

# SEE ALSO: https://github.com/ansible/ansible/issues/9526
- name: Copy Wordpress config file
  template: src=wp-config.php dest=/tmp/
- name: Move Wordpress config file
  command: mv /tmp/wp-config.php /srv/wordpress/

- name: Change ownership of Wordpress installation
  file: path=/srv/wordpress/ owner={{ wp_user }} group={{ wp_user }} state=directory recurse=yes

######################################################################## php
- name: Install php-fpm and deps
  yum: name={{ item }} state=present enablerepo=epel
  with_items:
    - php
    - php-fpm
    - php-enchant
    - php-IDNA_Convert
    - php-mbstring
    - php-mysql
    - php-PHPMailer
    - php-process
    - php-simplepie
    - php-xml
    - php-gd
    - php-mcrypt

- name: Disable default pool
  command: mv /etc/php-fpm.d/www.conf /etc/php-fpm.d/www.disabled creates=/etc/php-fpm.d/www.disabled
  notify: restart php-fpm

- name: Copy php-fpm configuration
  template: src=wordpress.conf dest=/etc/php-fpm.d/
  notify: restart php-fpm

- name: Start php-fpm Service
  service: name=php-fpm state=started enabled=yes
